# 集群标识
brokerClusterName = 351cluster
brokerName = broker-a
brokerId = 0

# Controller 模式配置
enableControllerMode = true
controllerAddr = 192.168.0.201:9770
allAckInSyncStateSet = true

# 存储配置
storePathRootDir = /root/rocketmq/rocketmq-5.3.2/data
storePathCommitLog = /root/rocketmq/rocketmq-5.3.2/data/commitlog

# 网络配置
listenPort = 10911
brokerIP1 = 192.168.0.201  # 当前节点 IP

# 数据保留策略
fileReservedTime = 48
deleteWhen = 04

# 功能开关
autoCreateTopicEnable = false
enablePropertyFilter = true
slaveReadEnable = true  # 允许从节点读（需配合 Controller 负载均衡）