listenPort=9876
enableControllerInNamesrv=false
[root@vm01 rocketmq]# cat controller.conf
controllerType = jRaft
enableElectUncleanMaster = false
notifyBrokerRoleChanged = true
controllerStorePath = /root/rocketmq/rocketmq-5.3.2/data/jRaftController
jRaftGroupId = jRaft-Controller
jRaftServerId = 192.168.0.201:9880
jRaftInitConf = 192.168.0.201:9880
jRaftControllerRPCAddr = 192.168.0.201:9770
jRaftSnapshotIntervalSecs = 3600
